version: '3.8'
services: 
  app: 
    # TODO: Configure build context
    build: . 
    container_name: demo_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      depends on: db
      
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
